[package]
name = "trouble-maker"
version = "0.1.0"
authors = ["ijoyce"]
edition = "2018"

[dependencies]
hyper = "0.12"
log = "0.4"
pretty_env_logger = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rand = "0.7"
futures = "0.1"
tokio = "0.1"
http = "0.1"
regex = "1"
config = "0.9"